LOCAL_FILES: E:/GoogleDrive/projects/andamento/receitas/
DIR_SAIDA: saida
DIR_FETCHER: scripts/fetcher

DIR_WEBDRIVER: C:/Users/dobraga/chromedriver.exe

DIR_SQL: scripts/sql

USER_SQL: root
PASSWORD_SQL: 123
DATABASE_SQL: receitas
HOST_SQL: db
PORT_SQL: 3306